import type { Metadata } from 'next';
import './globals.css';
import LogoutButton from '@/lib/logout';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<header className='bg-blue-700 mb-6'>
					<h1 className='text-3xl font-bold mb-8 text-white py-10 px-8'>
						Facebook
					</h1>
					<LogoutButton></LogoutButton>
				</header>
				<main className='px-8'>{children}</main>
			</body>
		</html>
	);
}
