import type { Metadata } from 'next';
import './globals.css';
import { ToastContainer } from 'react-toastify';
import UserAccountActionsButton from '@/components/UserAccountActionsButton';
// import { config as fontAwesomeConfig } from "@fortawesome/fontawesome-svg-core";
// import "@fortawesome/fontawesome-svg-core/styles.css";
import PendingFriendRequestsButton from '@/components/PendingRequestsButton';
import Link from 'next/link';
// fontAwesomeConfig.autoAddCss = false;

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<header className='bg-blue-700 mb-6 flex justify-between items-center py-10 px-8'>
					<Link href='/'>
						<h1 className='text-3xl font-bold text-white'>Facebook</h1>
					</Link>
					<div className='flex flex-row gap-4'>
						<PendingFriendRequestsButton />
						<UserAccountActionsButton />
					</div>
				</header>
				<main className='px-8'>
					<ToastContainer position='bottom-center' />
					{children}
				</main>
			</body>
		</html>
	);
}
